### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by AshKyd**

### CODE REVIEW

**Comment by AshKyd** [comment]
Oops, this doesn't work

**Comment by AshKyd** [comment]
this works now after updating package-lock.json. I've also fixed a Sass deprecatino & run the `npm run format` command

**Comment by AshKyd** [comment]
Wait, this doesn't work either. Newer Sveltekit builds into a different location by the looks. Let me look into it.

**Comment by AshKyd** [comment]
I see `svelte-package` handles creating the `dist/` folder. Yeah this is good to go then.

**Review by thomasbrettell — APPROVED** [review]

**Pull request merged**
